### ISSUE TITLE
Simplify Rythm template

### ISSUE THREAD

**Issue by greenlaw110** [robeio/robe#2]
The `@for` iteration in https://github.com/robeio/robe/blob/master/robe-crud/src/main/resources/templates-rythm/model.js could be simplified:

Original

```java
@for (io.robe.crud.helper.Model model: models) {{
...
}@if(model_index<models.size()){,}
}
```

Simplified version:

```java
@for (io.robe.crud.helper.Model model: models).join() {{
...
}}
```

Original version

```java
@if(model.isNullable()){false}else{true}
```

Simplified version

```java
@(model.isNullable())
```

**Comment by sinanselimoglu** [comment]
Ni Hao greenlaw110,

Thanks for your feedback. We refactored our code. 

Regards
Sinan

**Comment by greenlaw110** [comment]
Excellent! Thanks for using Rythm in your project :-)

**Comment by serayuzgur** [comment]
@greenlaw110 thanks to you for such a nice lib.
